Hello microverse merge to main branch
chudisoft/Hello-Microverse pull request #1
Opened 2023-05-30 15:43 UTC by chudisoft

Having created, tested, and  completed all requirements including:
1. Creation of .html file with header element.
2. Creation of .css file to style the above element.
3. Creation and usage of .gitignore file.

It's time to merge into the main branch.

2023-05-30 17:24 UTC, Strangeal requested changes
Hi @chudisoft, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)
## Highlights
Well-structured files ✅
All linter checks are passing ✅
Descriptive PR title with a great summary ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 17:24 UTC, Strangeal commented on README.md
- [ ] Kindly consider setting up your `linters` checks as specified in the project requirements. `Linter` checks are meant to help you write industry-standard code. To learn how to set up your `linters` kindly use this [link](https://github.com/microverseinc/linters-config/tree/master/html-css)

2023-05-30 17:24 UTC, Strangeal commented on README.md
- [ ] Kindly consider changing the license `path` in your `README` from `LICENSE` to `MIT` since the `MIT.md` file contains the license of the project. Currently, it's not working as it should and due to that when a user clicks on the license link in your `README` they only see a `404` page. See below for more details:
<img width="1369" alt="Screenshot 2023-05-30 at 13 51 01" src="https://github.com/NewtonOmbese/Hello-Microverse/assets/107192076/86be741a-ab9a-4d64-9b60-0d576b69ec8d">

2023-05-31 15:53 UTC, chudisoft commented on README.md
@Strangeal I have fixed this. Could you please check before I resubmit in portal?

2023-06-01 08:36 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @chudisoft, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 08:39 UTC, merged